# On every push this script is executed
on:
  push:
    branches:
      - sacred-timeline 
name: Build and deploy to GitHub Pages
jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    # Checkout
    - uses: actions/checkout@v2
    # Build & deploy
    - name: shalzz/zola-deploy-action
      uses: shalzz/zola-deploy-action@v0.12.0
      env:
        # Target branch
        PAGES_BRANCH: gh-pages
        # Provide personal access token
        TOKEN: ${{ secrets.TOKEN }}
